services:
  asr-service:
    container_name: asr-service
    image: dinohub-asr/whisper-asr-fastapi-service:0.5.2
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file: .env.dev
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - $PWD/asr_inference_service:/opt/app-root/asr_inference_service
      - $PWD/pretrained_models:/opt/app-root/pretrained_models
    ports:
      - 8001:8080
    command:
      #["bash"]
      [
        "fastapi",
        "run",
        "asr_inference_service/main.py",
        "--host",
        "0.0.0.0",
        "--port",
        "8080",
      ]
